//workout actions

const SET_WORKOUT = "SET_WORKOUT";
const CREATE_WORKOUT = "CREATE_WORKOUT";
const DELETE_WORKOUT = "DELETE_WORKOUT";
const EDIT_WORKOUT = "EDIT_WORKOUT";

//auth actions

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export {
  SET_WORKOUT,
  CREATE_WORKOUT,
  DELETE_WORKOUT,
  EDIT_WORKOUT,
  LOGIN,
  LOGOUT,
};
